matrix:
  include:
    - language: python
      python: "3.6"
      install:
      - pip install -U pip
      - pip install -r requirements.txt
      script:
        - pytest ./client/test.py

    - language: java
      sudo: true
      dist: trusty
      jdk: oraclejdk8
      before_script: 
        - cd server
        - chmod +x mvnw
  
      