matrix:
  include:
    - language: python
      python: "3.6"
      install:
      - pip install -U pip
      - pip install -r requirements.txt
      script:
        - pytest ./client/test.py

    - language: java
      jdk: oraclejdk8
      # before_install: cd server
      # before_script: cd server
      script: ./server/mvnw test -B
      