matrix:
  include:
    - language: python
      python: "3.6"
      install:
      - pip install -U pip
      - pip install -r requirements.txt
      - sh ./travis_setup.sh
      script:
        - pytest ./client/test.py
        - sh ./travis_run.sh
      after_success:
        coveralls

    - language: java
      sudo: true
      dist: trusty
      jdk: oraclejdk8
      before_script: 
        - cd server
        - chmod +x mvnw
  
      